### ISSUE TITLE
Account for empty block-fields so server doesn't Error out

### ISSUE THREAD

**Issue by josheigel** [NodeSquarespace/node-squarespace-server#108]
I saw the documentation where this tends to be a result of site in trial mode without the sandbox being enabled, however I have changed my template.conf to contain the `"sandbox": true` and employed the `sqs buster` command before and after changing that flag. Nothing seemed to work and this is the error that I get:
```
/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:1128
ata.data.layout.rows[ r ].columns[ c ].rows[ r2 ].columns[ c2 ].blocks.length;
                                                                      ^
TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:1128:129
    at Request._callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:412:9)
    at Request.self.callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1073:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1019:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

I am currently running version 0.12.7 of Node. Please let me know if you need anything else and thanks in advance!

**Comment by kitajchuk** [comment]
Hmm. Looks like a block data issue. Do you know which blocks you have on the page that is throwing this error? This would be coming specifically from squarespace:block-field tags in your template files.

**Comment by josheigel** [comment]
Sorry to waste your time, it was the block field:

**Comment by kitajchuk** [comment]
Weird. I suppose its possible to have a block id that technically has no "blocks" associated with it. Which seems like that may have been the case. Glad you figured it out. I'll keep this issue open and see if I can implement a condition around such a case so the server doesn't blow up.

**Comment by kitajchuk** [comment]
TODO:

Test empty block field
Determine appropriate place for an "empty block" condition in `squarespace-template`.

**Comment by kitajchuk** [comment]
Renamed the issue :D

**Comment by josheigel** [comment]
No worries, thank you so much!

**Comment by lyonsrob** [comment]
I'm getting the same error as above. Renaming the Footer block does get you passed the server crash, but the footer section is blank.

**Comment by lyonsrob** [comment]
Quick follow up, I just pulled the contents of the <footer> tag from my live site and created a new file 'block-footerBlocks.html' in the .sqs-cache directory. This works now without having to rename the footer id in the site.region file.
