### ISSUE TITLE
Use Squarespace Less compiler + GetTemplateTweakSettings API for local styles.

### ISSUE THREAD

**Issue by kitajchuk** [NodeSquarespace/node-squarespace-server#123]
This will be the new home of this issue until its resolved :D

**Comment by kitajchuk** [comment]
The endpoint for `GetTemplateTweakSettings` looks promising. I've been playing around with the lessc compiler as well and it seems promising beyond the system imports. The ones I know are these

- sqs-grid-breaker
- sqs-ui-font
- social-icon-font ( deprecated )

I have a local branch as of right now that I have been playing with this stuff in. Your outlined plan of attack generally covers the gist of what would need to be done.

It's a bit more involved since implementing the new compiler and resolving any other of the Less issues shouldn't require the usage of the node server to change in any way.

I'm going to avoid merging your PR since the full-scale implementation of this is quite large. The middleware would require a small update as well and I still see some unkowns.

The following is an updated scope of this implementation as I see it.

1. Update `node-squarespace-middleware` to consume data from `api/template/GetTemplateTweakSettings` when logging in. This will amend the [getAPIData](https://github.com/NodeSquarespace/node-squarespace-middleware/blob/master/squarespace-middleware.js#L156) method which pre-fetches necessary schemas for the node server to operate effectively.
2. Implement the `lessc` compiler as an executable within the `node-squarespace-server` module at `bin/lessc`. This way the module ships with it and developer usage of the server doesn't change.
3. Utilize `rawLess` from the `GetTemplateTweakSettings` information, parsing out only the Squarespace System portion ( not sure how hard/easy this will be ). Since `rawLess` retains comments still, it could be as easy as having folks use a comment like `/* node-squarespace-server hook */` as the first line of their styles to parse it all out.
4. Parse the remote `site.css` absolute `<link />` out of rendered local template headers so only local styles render locally.
5. Swap the current node Less compiler for the `lessc` compiler using child_process.exec.
6. Use the `GetTemplateTweakSettings` information to create a tweak variables Less stylesheet for use with the `lessc` compiler.
7. Compile the styles in order of `template.conf:stylesheets`, prepending `sqs-system-raw.less` and `sqs-tweak-variables.less`. The `reset.css` file will be accounted for as well if applicable. I'll note here that the system imports mentioned above that get used in template Less files would still not work correctly. The only thing I can think is that as long as you are using them, the `rawLess` would potentially include those files' imported contents - though that doesn't seem likely.

I think this generally makes sense. @Aeon if you have any thoughts/insights on the system imports, please share them here since that seems like the biggest hurdle still in this whole process.

**Comment by kitajchuk** [comment]
+ @Aeon

**Comment by Aeon** [comment]
context:
See https://github.com/Squarespace/less-compiler

Benefits:
 1. faster than lessjs
 2. supports squarespace-specific LESS features
   a. SquareSpace "tweaks" concept: http://developers.squarespace.com/style-editor/

   b. escaping variables to be used as selectors (see http://stackoverflow.com/questions/13553669/less-css-escape-interpolated-string-for-multiple-selectors) - see this example from `mobile-nav.less`

      ```less
    (~"@{mobileEl}") { ... }

**Comment by kitajchuk** [comment]
Perfect, thanks @Aeon :D

**Comment by kitajchuk** [comment]
Implemented the middleware portion since that won't have any impact on current users of the server other than the initial fetch time. https://github.com/NodeSquarespace/node-squarespace-middleware/commit/16939fe2686fd33efbe68e6c1fb34561ead8fbd6

@Aeon - Working on the rest of the implementation. When I have a stub in some working order I'll push the branch up so you can have a peek at it.

**Comment by kitajchuk** [comment]
@Aeon - Initial implementation is in this branch: https://github.com/NodeSquarespace/node-squarespace-server/tree/use-sqs-less-compiler.

Something is still missing though. I'm afraid it seems like there's still more Less/CSS that gets compiled into the global site.css file that maybe isn't in the raw tweak data.

A couple of notes. There is a `%SQUARESPACE_CDN%` placeholder that needs to be switched out. I am currently just dumping for an empty string. The server picks up requests to `/universal/*` and puts a redirect through to the remote URL. So, not sure what's missing yet.

I'll dig into it more later but this is a good stub if you're interested in looking it over.

**Comment by Aeon** [comment]
I've opened an issue with SQS support, but they basically said that they do not have resources to either provide an API, or to include the secret sauce in the template.git. They didn't provide any detailed reasons though, trying to find out if they might do it in the future or not.

**Comment by kitajchuk** [comment]
@Aeon - I'm sure they don't have a vested interest in providing tools to help resolve this on their end. That's cool though.

Anyway, I have a personal resolve I have been using to get by a little better. I just pushed the branch that contains the hack: https://github.com/NodeSquarespace/node-squarespace-server/tree/static-remote-css-local-hack.

Essentially, I never use the npm installed version of the server. I always run against my local copy in git. I have a Fish function for this, but you can easily make a bash alias as well.

The gist of it is that you manually hit your static site css and copy just the first portion up to your personal template code and dump it in a css file in a directory that is ignored by the repository: `./local/sqs-static-site.css`. If you clone the repo, fetch and switch to the `static-remote-css-local-hack` branch you can run the server locally in this way. It's really just a temporary resolve until a better way is found.

Anyway, that alias would look something like this in your `.bash_profile`:

`alias sqs-loc="node ~/path-to-local-copy-of/node-squarespace-server/bin/squarespace-server server --port=8080 --reload"`

Anyway, will keep on tinkering on it and try to figure out a true resolve :P
