### ISSUE TITLE
Make browser-sync reload work more than 2 times in a session

### ISSUE THREAD

**Issue by kitajchuk** [NodeSquarespace/node-squarespace-server#126]

**Comment by kitajchuk** [comment]
Sometimes it does, and sometimes it doesn't. WTF!?

**Comment by mattnull** [comment]
I am noticing that this mainly happens for us when we use a template other than base-template

**Comment by mattnull** [comment]
I believe the problem I am seeing is related to this issue - 
`
/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:886
    typeName = pageJson.collection.typeName;
                                  ^
TypeError: Cannot read property 'typeName' of undefined
    at getTemplateKey (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:886:35)
`

**Comment by kitajchuk** [comment]
I lied, browser-sync has been working fine...
