### ISSUE TITLE
Error with Wells template

### ISSUE THREAD

**Issue by skrichten** [NodeSquarespace/node-squarespace-server#132]
I am trying to use the Wells template from Squarespace as a starting point and I get this error...

 sqs-log Error requesting block json from Squarespace with midd
leware => Empty block JSON
> sqs-log Error requesting block json => Empty block JSON

The site still loads but the individual gallery images don't show. Hard to say if this error is related to that  issue however.  Any ideas?

**Comment by kitajchuk** [comment]
I can pull the Wells template and take a look at it.

**Comment by skrichten** [comment]
The problem with the photo gallery is this...
```
{.image?}{@|image load-false}{.end}
{.video?}{@|video load-false}{.end}
```
I guess this isn't supported yet.  I think I ran into similar problems with the momentum template.  Any good workarounds for this kind of thing?  Is there an equivalent "if" statement I could use?

**Comment by skrichten** [comment]
Oh, I see ".or" works now!  So I replaced that bit with this...

```
{.video?}{@|video load-false}
{.or}{@|image load-false}{.end}
```
That'll work for now.

Still not sure what the empty block error is about though.

**Comment by kitajchuk** [comment]
Are you using the latest version of the server? More specifically, the latest jsont node module: https://github.com/NodeSquarespace/node-squarespace-jsont

**Comment by kitajchuk** [comment]
We don't have a `.image?` predicate. We have the `.main-image?` predicate. Is there documentation on `.image?` ?

**Comment by kitajchuk** [comment]
Basically, we are currently supporting what is documented here:

http://jsont.squarespace.com/
http://developers.squarespace.com/quick-reference/
http://developers.squarespace.com/json-formatters/

**Comment by skrichten** [comment]
I don't know why .image? isn't documented (they use it in their templates quite a lot), but it has the same function as .video? except it checks if the gallery item is an image of course.

**Comment by kitajchuk** [comment]
Oh that's rad. I can support that easily enough :D

**Comment by skrichten** [comment]
"Are you using the latest version of the server?"

I installed the server yesterday.  When I created the site, I also created most of the demo content in the squarespace admin.  Perhaps some secondary item didn't get created that should have.  Probably best to ignore it if you haven't seen any obvious issue.  I'll let you know if find anything.

"Oh that's rad. I can support that easily enough :D"
Cool!

**Comment by kitajchuk** [comment]
What are you scoped into when you are using `.image?`

**Comment by skrichten** [comment]
".repeated section items" in a gallery.list template.  Same use case as ```.video?```

**Comment by kitajchuk** [comment]
Yeah, I'm actually going through the Wells template now and I just caught that :P

**Comment by kitajchuk** [comment]
Alright. I just pushed and published a couple of new predicates for the node-squarespace-jsont module. In order to pull these into your server install you'll want to run `npm install -g node-squarespace-server` and you should get `node-squarespace-jsont@0.1.19`.

**Comment by skrichten** [comment]
Cool thanks!

**Comment by kitajchuk** [comment]
Let me know if it works out for you :)

**Comment by skrichten** [comment]
It does work, thanks again!  The empty block JSON error was coming from an empty text block in the header content area, so I think we can just close this.

**Comment by kitajchuk** [comment]
@skrichten - Cool! The empty block JSON is more of a warning, though its logging as an error right now. The node middleware cannot know whether a block-field has content or not until its attempted to request that information from Squarespace. Hence, the empty block messaging when it comes back as such.
