### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by mwickett** [NodeSquarespace/node-squarespace-server#134]
Getting this error:

````
/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:476
        rendered += templates.regions[ regionKey ].replace( SQS_MAIN_CONTENT, 
                                                  ^
TypeError: Cannot read property 'replace' of undefined
    at Object.renderTemplate (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:476:51)
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-server.js:228:29
    at /usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:311:13
    at Request._callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-middleware/squarespace-middleware.js:234:9)
    at Request.self.callback (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1063:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-squarespace-server/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:129:20)
````

I'm using a custom template (started from base-template). I have a site-wide password turned on and configured properly in template.conf.

If I run `sqs server` again, I get:

````
undefined:0


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-util.js:90:22
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-util.js:77:17
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
````

Running `sqs buster` and then `sqs serve` again gets the first error again.

**Comment by kitajchuk** [comment]
Looks like the server believes your request is for a static page. Can you paste your page json. Also, what is the name of your `.page` template file?

**Comment by mwickett** [comment]
I should have included that we are using some static pages - does node-squarespace-server not support them? The page is called `home.page`

To get the page json, I'm getting output of `https://<site-url>?format=json-pretty` ? (Just clarifying)

**Comment by kitajchuk** [comment]
Static pages are supported so that's cool. But issues related to how the server figures out what pieces of your template to put together for any given request are usually easier to debug with the `json` output of said request. You can just hit this thread with the `collection` object output when you use `?format=json` on the request.

**Comment by mwickett** [comment]
I was just reading over the closed issues related to static page implementation. 

Collection object output:

```
collection: {
id: "55f05817e4b0922a8954cdec",
websiteId: "55c51a9ae4b0b6679a5aca46",
enabled: true,
starred: false,
type: 7,
ordering: 2,
title: "Home",
navigationTitle: "Home",
urlId: "home",
itemCount: 0,
updatedOn: 1441814551001,
description: "",
features: {
relatedItems: {
isEnabled: false
},
productQuickView: {
isEnabled: false
}
},
folder: false,
dropdown: false,
tags: [ ],
categories: [ ],
homepage: true,
typeName: "home",
regionName: "home",
synchronizing: false,
fullUrl: "/",
typeLabel: "home",
passwordProtected: false
},
````

Sorry the output is kind of fugly.

**Comment by kitajchuk** [comment]
@mwickett - Could you also paste your `template.conf`? You can leave anything out you don't want in the thread, I just need to see your `layouts` information.

**Comment by mwickett** [comment]
Sure thing.

```
{
  "name" : "inHouse v3",
  "author" : "Michael Wickett",

  "layouts" : {
    "default" : {
      "name" : "Default",
      "regions" : [ "site" ]
    }
  },

  "navigations" : [ {
      "title" : "Main Navigation",
      "name" : "mainNav"
  },
  {
      "title" : "Footer Navigation",
      "name" : "footerNav"
  } ],

  "stylesheets" : [
    "bootstrap.css",
    "font-awesome.css",
    "creative.css"
  ],

  "systemCollections" : [ "products" ],

  "server": {
    "siteurl": "…",
    "password": "<password>"
  }
}
```

**Comment by kitajchuk** [comment]
Okay, cool. I think I see where the hiccup is in looking up the region to wrap the static page in. I should be able to resolve this pretty easily.

**Comment by kitajchuk** [comment]
Hmm. It seems weird that you have a `regionName ` of "home" yet have no `home` layout specified in your template.conf...

**Comment by kitajchuk** [comment]
And if you haven't manually set a layout for that static homepage in the CMS, the regionName should be `default` from my understanding.

**Comment by kitajchuk** [comment]
I guess either way it doesn't matter. The server just needs to always resolve to using the default layout when all other lookup attempts result in nothing being found to use.

**Comment by mwickett** [comment]
Yes, my understanding was that it would drop any static page content into `{squarespace.main-content}` without requiring individual layouts.

It's quite possible that I've buggered something up...I can try adding another layout if you think it would help.

**Comment by kitajchuk** [comment]
You're fine. I'm guessing this commit, 4fb8ded8e6f7060e513753378f89c7ed09ce4e7e, should work out for you. Try an update, + node-squarespace-server@0.4.4 - this is the new version. Let me know if you still have issues and we'll keep hacking away at it.

**Comment by mwickett** [comment]
After updating, the site loads locally, although not fully. Referenced the error [here](https://github.com/NodeSquarespace/node-squarespace-server/issues/133#issuecomment-143868653)

**Comment by kitajchuk** [comment]
Closing this one since I think we are onto one issue at this point... I think :P

https://github.com/NodeSquarespace/node-squarespace-server/issues/133
