### ISSUE TITLE
External links in submenu doesn't work.

### ISSUE THREAD

**Issue by filipdanisko** [NodeSquarespace/node-squarespace-server#137]
Hi guys,
I just ran to issue with navigation. I created navigation with folder wich has external links in it.

Squarespace returning to template this:
``` json
{
 "active": false,
 "externalLink": Object,
 "folderActive": false
}
```

Node-server returning this:
``` json
{
 "active": false,
 "collection": null,
 "folderActive": false
}
```
Are external links not supported or is it a bug?

btw: keep up a good work it is really helpful development tool.
Thanks.

**Comment by kitajchuk** [comment]
It's very likely we aren't accurately capturing externalLinks in folders when we piece together the navigations. I'll take a peek around at this :)

**Comment by kitajchuk** [comment]
This is a good find. It seems there have been a couple of oversights when working with navigations locally. Especially the use case of indexes and folders. I have this exact issue setup on my current site and am debugging locally now. Should be an easy fix here soon :P

**Comment by kitajchuk** [comment]
@filipdanisko - Just pushed an update for this. You were right, we were not replicating the condition for `externalLinks` in index/folder navigations. Should be working now though. Published a new patch for the server `+ node-squarespace-server@0.4.7`.

**Comment by filipdanisko** [comment]
Awesome I just pull the update and test it out. Everything seems ok. Thank you for quick fix. :)

**Comment by kitajchuk** [comment]
Sweet!
