### ISSUE TITLE
Less / CSS files concatenated in reverse order?

### ISSUE THREAD

**Issue by skrichten** [NodeSquarespace/node-squarespace-server#141]
Looking at my site.css, it looks like reset.css is the last file and I see the last .less file from my config at the top.  So, it looks like the order is reversed.

**Comment by kitajchuk** [comment]
Just pushed the fix for this: d7bb5c6583776ba54aeed236f06f4fd1890dedec

Published the new server: `+ node-squarespace-server@0.4.11`

:)
