### ISSUE TITLE
Updating to node-squarespace-server@0.4.13 removes External Links from Navigations

### ISSUE THREAD

**Issue by jasonbarone** [NodeSquarespace/node-squarespace-server#144]
I just updated to the latest version it looks like External Links within Navigations are not rendering.

**Comment by michaek** [comment]
This does appear to be a regression in 0.4.13. Links are missing in navigations in 0.4.13, but downgrading to 0.4.12 restores them. Possibly something missed in a37f111057c974e95b52e6a11c2dee97014dc95a ?

**Comment by kitajchuk** [comment]
Yeah, I missed something in there. Sorry guys, been crazy busy so I haven't been able to get around to some of these issues yet :/

**Comment by kitajchuk** [comment]
Looks like my check for `enabled` links broke this since `externalLinks` get their enabled attribute set to false. Pushed a fix. New version: + node-squarespace-server@0.4.17
