### ISSUE TITLE
MainImage section missing in navigation data

### ISSUE THREAD

**Issue by skrichten** [NodeSquarespace/node-squarespace-server#146]
On Squarespace I get the mainImage section in navigation items, but I'm not seeing it when using the local server.  I know that it might be unusual to need that, but it would be a big help to me right now.

**Comment by kitajchuk** [comment]
Can you give me an example?

**Comment by kitajchuk** [comment]
Never mind the example - I have one I can work with on my project.

**Comment by kitajchuk** [comment]
Looks like the data you get back from `api/commondata/GetCollections` is a subset of a full collection object for each collection. This endpoint returns full data for a collection: `api/commondata/GetCollection/?collectionId={id}`. Looks like the data fetching will need to first pull all collections and then iterate them all to pull full collection data. Tricky.

**Comment by kitajchuk** [comment]
This will increase the amount of time the data fetching takes.

**Comment by skrichten** [comment]
This is not a big deal for me anymore.  I just put placeholder rectangles where the images should be.  That was enough to get me past this.

**Comment by kitajchuk** [comment]
Its cool. This was a good callout either way. The fix actually took place entirely in the middleware: https://github.com/NodeSquarespace/node-squarespace-middleware/commit/222588273665bc3f0d8a3a444213142f0566b341. If you run an `npm install -g node-squarespace-server` you should get the new middleware version which fetches full collection data. After that you should have the `mainImage` information to work with locally as well.

Even though its not a blocker for you, its nice to get the server as one-for-one as it can be with what you expect on Squarespace's end. So, thanks for finding these bugs for me. Its a big help :)
