### ISSUE TITLE
Development server renders nav from top node, while live server renders children

### ISSUE THREAD

**Issue by michaek** [NodeSquarespace/node-squarespace-server#149]
I created a site by copying the [Pacific theme](http://www.squarespace.com/templates/?q=pacific%20businesses), and the navigation configuration contains a top-level "Welcome" with a handful of children. On the live server, the "Welcome" node is not rendered, while on the dev server it is.

Here's the configuration:
![screen shot 2015-11-05 at 2 17 09 pm](https://cloud.githubusercontent.com/assets/155459/10982042/4dfd3aa6-83c8-11e5-8623-85d689cc1151.png)

Live server:
![screen shot 2015-11-05 at 2 20 35 pm](https://cloud.githubusercontent.com/assets/155459/10982067/710afca4-83c8-11e5-9b23-ac92bd4c64f7.png)

Dev server:
![screen shot 2015-11-05 at 2 21 25 pm](https://cloud.githubusercontent.com/assets/155459/10982084/930ad28e-83c8-11e5-8fa1-e20c9dda1db1.png)

Sorry for using screenshots to communicate the issue - I'm not yet sure what the best way is to output and report useful data!

**Comment by kitajchuk** [comment]
Weird. What does the navigation block partial look like? Can you paste it in here?

**Comment by michaek** [comment]
I'm pretty sure this is unchanged from the template:

```html
{.section items}<div id="mainNavWrapper" class="nav-wrapper show-on-scroll">
  <nav id="mainNavigation" data-content-field="navigation" >
    {.repeated section @}
      {.collection?}
        {.index?}
          {.if collection}
            {.if collection.homepage}
              {.repeated section items}
                {.section collection}
                  {.collectionTypeNameEquals? gallery}
                  {.or}
                  <div class="index home">
                    <a href="/#{collection.urlId}-section">
                      {navigationTitle}
                    </a>
                  </div>
                  {.end}
                {.end}
              {.end}
            {.end}
            <div class="index{.if collection.homepage} base{.end}{.if active} active{.end}">
              <a href="{collection.fullUrl}">
                {collection.navigationTitle}
              </a>
            </div>
          {.end}
        {.or}

        {.folder?}
        <div class="folder{.if folderActive} active{.end}{.section collection}{.if homepage} homepage{.end}{.end}">
          <input type="checkbox" name="folder-toggle-{collection.id}" id="folder-toggle-{collection.id}" class="folder-toggle-box hidden" />
          <label for="folder-toggle-{collection.id}" class="folder-toggle-label" onclick data-href="{collection.fullUrl}">{collection.navigationTitle}</label>
          <div class="subnav">
          {.repeated section items}

            {.collection?}
            <div class="collection{.if active} active{.end}">
              <a href="{collection.fullUrl}">
                {collection.navigationTitle}
              </a>
            </div>
            {.end}
            {.section externalLink}
            <div class="external">
              <a href="{url}"{.section newWindow} target="_blank"{.end}>
                {title}
              </a>
            </div>
            {.end}
          {.end}
          </div>
        </div>
        {.or}

          {.section collection}
          <div class="collection{.if active} active{.end}{.if homepage} homepage{.end}">
            <a href="{fullUrl}">
              {navigationTitle}
            </a>
          </div>
          {.end}

        {.end}
      {.end}
      {.or}
        {.section externalLink}
        <div class="external">
          <a href="{url}"{.section newWindow} target="_blank"{.end}>
            {title}
          </a>
        </div>
        {.end}

      {.end}

    {.end}
  </nav>
</div>
<!-- style below blocks out the mobile nav toggle only when nav is loaded -->
<style>.mobile-nav-toggle-label { display: inline-block; }</style>
{.end}
```

It seems like it might be going into the folder code path, though the "Welcome" node is an index?

**Comment by kitajchuk** [comment]
Replicated this locally with the Pacific template so I think I can fix it. It looks like I'm not currently supporting the `index?` predicate, just the `folder?` one.

**Comment by kitajchuk** [comment]
An index only renders its children, not the index root, if its set as the homepage.

**Comment by kitajchuk** [comment]
Nvm - that's hardcoded into the template. Looks like all it needed was to support the `index?` predicate.

**Comment by kitajchuk** [comment]
Looks like a fix - but it was actually in the `jsont` module - https://github.com/NodeSquarespace/node-squarespace-jsont/commit/8247659f76422501575b21de9a7a6c0696d01cd7. I bumped the version for the server though, so you should be able to run an update and pull in the latest `node-squarespace-jsont` as well.

:)

**Comment by michaek** [comment]
Looks good. Thanks!
