### ISSUE TITLE
.if statement "or" operator crashing server

### ISSUE THREAD

**Issue by jasonbarone** [NodeSquarespace/node-squarespace-server#150]
Looks like using Squarespace .if statement operators are crashing the server returning the following error. The piece of code is: `{.if categoryFilter || tagFilter}`

```
/usr/local/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/jsontemplate.js:291
            var value = context[name];
                               ^

TypeError: Cannot read property 'categoryFilter || tagFilter' of null
```

**Comment by kitajchuk** [comment]
Yeah, I know about this one. It's an issue logged here for the `jsont` module:

https://github.com/NodeSquarespace/node-squarespace-jsont/issues/21

**Comment by kitajchuk** [comment]
Going to close this one here since it can be handled on the `jsont` modules end.
