### ISSUE TITLE
Continuous "Fetched fullData" entries after logging in

### ISSUE THREAD

**Issue by jasonbarone** [NodeSquarespace/node-squarespace-server#154]
Running into an issue with multiple sites that previously worked without issue. After clicking Login to authenticate, the server will continuously log "Fetched fulldata" entries while the browser shows the login animation. I end up having to stop the server and try again a few times until it successfully get through.

Any idea what could be causing that?

<img width="406" alt="screen shot 2015-12-11 at 7 22 50 pm" src="https://cloud.githubusercontent.com/assets/545055/11758752/fb1977fa-a03c-11e5-9473-3b0d7d959f0d.png">

**Comment by kitajchuk** [comment]
It's fetching the full data for all the collections your site has. How many collections do you have? This is the endpoint that shows all collections: `/api/commondata/GetCollections/`. The endpoint to get one collection is this: `/api/commondata/GetCollection/?collectionId={id}`.

**Comment by jasonbarone** [comment]
When the server boots up perfectly, there's no "fetched" line, it just goes straight into the server without showing this stuff. I'm only seeing these "fetched" lines when the server is not actually booting up. It hangs during the after-login indicator. I haven't ever had it get hung up after authentication. I'll keep playing with it.

**Comment by kitajchuk** [comment]
I'm experiencing this a well now. Must be something related to the process for fetching collection data up front. I'll get into it and see what's up.

**Comment by kitajchuk** [comment]
Are you using the `.sqsrc` file for login? Seems that was the issue for me. Maybe I'll take a look at `node-keytar` as that seems like a better solution anyway :)

**Comment by kitajchuk** [comment]
After switching to keytar for login creds this went away for me.
