### ISSUE TITLE
New version (w/node-keytar) on Windows

### ISSUE THREAD

**Issue by skrichten** [NodeSquarespace/node-squarespace-server#156]
I was getting an error today, so I thought I would try updating to the latest version.  I was unable to install it on my Windows 10 machine, presumably because of the addition of node-keytar.  I think it is related to node-gyp.  It's a total PITA to get that working correctly on Windows.  I always got node-gyp errors/warnings when installing this package (and others), but this time it seems to be fatal.  Before, the errors were only for "optional dependencies" like bufferutil.  Any chance node-keytar can be made an optional dependency?

**Comment by kitajchuk** [comment]
I can look into that. I was looking for a good way to store creds for auto login and node-keytar seemed like a light-weight hit for it. It's a bummer it doesn't work on Windows - though the README mentions that it should... Sorry for the inconvenience.

**Comment by skrichten** [comment]
It can probably work on Windows IF you can get node-gyp working, but you have to install a bunch of stuff and it isn't straight forward.  For example, they tell you that you need to install the windows 7 sdk, but that won't install on windows 10.

**Comment by kitajchuk** [comment]
Removed keytar and am trying out xkeychain. Still requires node-gyp though so don't know if this makes it any better. The real reason to remove keytar was a dependency it had forcing the server not to run on newer versions of node.
