### ISSUE TITLE
Issue compiling less files

### ISSUE THREAD

**Issue by schikulski** [NodeSquarespace/node-squarespace-server#160]
Having the same issue as #115 I think.

I created the pages directory, but same result.

```
sqs buster && sqs server --reload                                                                    ⏎
> sqs-log Clear local cache
> sqs-log Squarespace server running in livereload mode
> sqs-log Issue compiling less file `mixins.less` => 'sqs-ui-font.less' wasn't found
> sqs-log Issue compiling less file `base.less` => .transform is undefined
> sqs-log Issue compiling less file `blog.less` => .border-box is undefined
> sqs-log Issue compiling less file `index.less` => 'sqs-ui-font.less' wasn't found
> sqs-log Issue compiling less file `mobile.less` => 'sqs-grid-breaker.less' wasn't found
> sqs-log Squarespace server running localhost:5050

```

**Comment by kitajchuk** [comment]
Well, it looks like you're not getting an actual error thrown, just the logs noting that the automagical LESS that Squarespace offers isn't available locally - which does suck. You'll notice there is a lot of information about trying to resolve the local LESS issue here: https://github.com/NodeSquarespace/node-squarespace-server/issues/123

I know you can hit the less files on universal which means there is a possibility that they could still be loaded locally, but the server would have to include them as core references. These are the ones I am aware of:

http://squarespace.com/universal/styles-v6/social-icon-font.less
http://squarespace.com/universal/styles-v6/sqs-grid-breaker.less
http://squarespace.com/universal/styles-v6/sqs-ui-font.less

I think a resolve could be on the horizons, but for now thanks for baring with me.
