### ISSUE TITLE
"sqs server" command hangs on "Fetching data from Squarespace..."

### ISSUE THREAD

**Issue by derekduoba** [NodeSquarespace/node-squarespace-server#164]
The "sqs server" command stops on "Fetching data from Squarespace...," waits several minutes, logs back into Squarespace, and attempts to fetch data again. This continues until I ctrl+c out of the application.

Output:
```
sqs server
> sqs-log Issue compiling less file `base.less` => 'sqs-grid-breaker.less' wasn't found
> sqs-log Squarespace server running localhost:5050
> sqs-log Logging into Squarespace...
> sqs-log ...Logged in to Squarespace
> sqs-log Fetching data from Squarespace...
```

The server entry in template.conf:
```
...
  "server": {
    "siteurl": "https://dduoba.squarespace.com",
    "password": "[SOME PASSWORD]",
    "sandbox": true
  }
...
```

I am attempting to run this with a new-ish developer trial account. My local environment is a mac with node.js v5.6.0

**Comment by derekduoba** [comment]
This issue appears to have resolved itself. Perhaps there was a network issue?

**Comment by kitajchuk** [comment]
Yeah - you can encounter network issues sometimes. I get it from time to time. Annoying, but not much you can do. Possibly an offline mode could help a bit. As long as you have local cache and don't need CMS changes pulled down for what you are working on.
