### ISSUE TITLE
"Fetching data..." hangs when website has no pages

### ISSUE THREAD

**Issue by scottyeck** [NodeSquarespace/node-squarespace-server#166]
Likely, this is unavoidable, since obviously, when a website has no pages, there is nothing to fetch. Duh. That said, the docs might benefit from a quick mention of this under _Troubleshooting_ (which I'm happy to write). **Or**, even better yet, it'd be awesome if an error was thrown if the response contains insufficient data to start the _Express_ instance.

Mostly, I'm an idiot and would love it if no one else has to scratch their head regarding a brain fart like mine. Feel free to ignore this under the assumption that no one else will be as stupid as me. :stuck_out_tongue_winking_eye:

**Comment by mwickett** [comment]
This issue saved me some pain. I've used this awesome tool (Thanks @kitajchuk!) before but never on a bare developer template. Spent 5 minutes fiddling before I looked here and noticed this.

Second the idea of adding a note in readme and a more descriptive error.

**Comment by mwickett** [comment]
Follow-up - I think this issue should actually be in [node-squarespace-middleware](https://github.com/NodeSquarespace/node-squarespace-middleware) as it handles the job of interfacing with your Squarespace instance.

Also, I *think* it's less about having `null` pages and more about there not being a homepage set (of course, to have a homepage you have to have at least one page).
