### ISSUE TITLE
sqs server doesn't start server

### ISSUE THREAD

**Issue by wearenifty** [NodeSquarespace/node-squarespace-server#169]
When I run `sqs server` nothing happens. No errors, no indication that the server has started - which it hasn't. When I change template.conf I do receive a console.log message indicating the file was reloaded. How can I debug the issue to figure out why the server isn't starting?

**Comment by jasonbarone** [comment]
The first thing to do is to open up the command line and run `sqs`. That should return the help menu in the command line. Does that work?

If so, then you at least have the command line tool installed.
If not, then it sounds like it might not be installed globally.

**Comment by wearenifty** [comment]
yes. it's installed. the command runs, but it hangs. if I run sqs server in an arbitrary directory it outputs an error message as it should but in my squarespace template directory which is configured correctly I don't receive any errors or a console.log that the server has started listening.

**Comment by wearenifty** [comment]
I dove into the code and figured it out. The server was hanging because of a ENOENT error caused by an incorrect path trying to read the .region files. The path assumption is that those files are in the template root - but in fact, they are in the blocks/ directory. Not sure if this is because I'm using a totally custom squarespace template or not. Anyway, I fixed the issue by updating the path
