### ISSUE TITLE
Support --auth argument to selectively impersonate Squarespace authenticatedAccount session

### ISSUE THREAD

**Issue by jasonbarone** [NodeSquarespace/node-squarespace-server#187]
Would be useful to selectively impersonate an authenticatedAccount session so we can test code with or without the `authenticatedAccount` JSON in Squarespace.

**Comment by kitajchuk** [comment]
Published new version – [node-squarespace-server@0.5.31](https://www.npmjs.com/package/node-squarespace-server)
