### ISSUE TITLE
JSON boolean value converted to a number in Equal Predicate

### ISSUE THREAD

**Issue by dmitrykiselyov** [NodeSquarespace/node-squarespace-server#191]
JSON boolean value converted to a number in Equal Predicate.
For example `{.equal? collection.homepage true}` will not work, but `{.equal? collection.homepage 1}` will be.

Brandon @kitajchuk, Thank you very much for this wonderful tool.

**Comment by kitajchuk** [comment]
Interesting – is this a direct use case? For boolean conditions you could also just us the "if" predicate. `{.if collection.homepage}Homepage Stuff{.end}`

**Comment by dmitrykiselyov** [comment]
Yes, I used once 😄 before I discovered the possibility of using `if` statement.
