### ISSUE TITLE
Live Reload? 

### ISSUE THREAD

**Issue by lifeinchords** [NodeSquarespace/node-squarespace-server#193]
Hi,

I'm just getting started with Squarespace dev mode, and this project.
I got my basic dev template running locally on `localhost:5050`, with one + only template `site.region`, under the project root. 

I'm making simple HTML changes to this template in Sublime while the `sqs` server running, and I'm seeing this output in my terminal: 

```
> sqs-log Updated template file site.region
> sqs-log Reloaded local template
```

but the browser isn't refreshing/updating/reloading my changes.

I was under the impression live reload was a feature via this: https://github.com/NodeSquarespace/node-squarespace-server/pull/125/files

I also tried running the server with a flag, as `sqs server --reload`, after seeing it mentioned in some of the comments in that PR, but if it is included, why isn't it listed as a command in the `sqs` list?

[
![screen shot 2016-07-07 at 1 39 13 pm](https://cloud.githubusercontent.com/assets/716168/16663038/97c7d736-4448-11e6-8ad3-cd67de925e5f.png)
](url)

You can see here I've modified my source, the H1 to `ashley 9033` and the DIV under Inspect Element hasn't updated.

I think I'm missing something.. any thoughts?  
~steven

**Comment by kitajchuk** [comment]
Reload is no longer a part of the node server core. I use browser-sync to proxy my node server instance and handle live reloading. This is useful when using different project scaffolds. I use the browser-sync webpack plugin since I use webpack for my project pipeline.
