### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by mwickett** [NodeSquarespace/node-squarespace-server#198]
This is not an issue. This is a big 'ol "thank you!" Brandon, for all the energy and time you put into this project.

Until the official dev server, this project was a key part of my workflow. Thanks for creating and maintaining it, and for sharing it with the community.

You're awesome.

**Comment by kitajchuk** [comment]
Thanks for the kind words! It was a really fun effort overall and we got an official dev server out of it! This open source project is the keystone that got Squarespace to begin working on official developer tools. Feels great not to work on it anymore, but it was definitely a blast to do it.

Happy developing :)
