### ISSUE TITLE
Collection Comment support

### ISSUE THREAD

**Issue by yatryan** [NodeSquarespace/node-squarespace-server#97]
Comments on collection items are not rendering locally. Both the input box and any existing comments are not displaying. The JSONT is:
```
{@|comments}
```

This might be more appropriate in [kitajchuk/node-squarespace-middleware](https://github.com/kitajchuk/node-squarespace-middleware)

**Comment by kitajchuk** [comment]
Yeah, comments are tough. The reason items like that don't render locally is because I have yet to look into how to use the API to get rendered comments. Any insights would be wonderful. It can be tedious figuring out how to get some of this stuff to work locally for sure...

**Comment by kitajchuk** [comment]
Closing this as its an issue for the jsont parser [here](https://github.com/NodeSquarespace/node-squarespace-jsont/issues/8)
